version: "3"
virtualmachines:
- name: workshop-host
  image: instruqt/docker-28-3
  shell: /bin/bash
  machine_type: n1-standard-1
- name: localhost
  image: instruqt/docker-28-3
  shell: /bin/bash
  machine_type: n1-standard-1
  memory: 4096
  cpus: 1
